name: rmg_env
channels:
  - defaults
  - rmg
  - rdkit
  - conda-forge
dependencies:
  - beautifulsoup4
  - cairo
  - cairocffi
  - coverage
  - cython >=0.25.2
  - docutils
  - django >=2.2
  - gprof2dot
  - graphviz
  - jinja2
  - libgcc
  - markupsafe
  - matplotlib >=1.5
  - mopac
  - nose
  - numpy >=1.10.0
  - openbabel
  - psutil
  - pydas >=1.0.1
  - pydot
  - pydqed >=1.0.0
  - pyparsing
  - python >=3.7
  - quantities
  - scipy
  - symmetry
  - rdkit >=2018
  - xlrd
  - xlwt
